version: "3.7"

networks:
  core:

services:

  product_db:
    image: "postgres:12.1"
    container_name: "product_db"
    hostname: "psql01-host"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=7UQxgBfWYsvprniok4fc
      - TZ=America/Sao_Paulo
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - core
